services:
  
  rabbitmq:
    image: rabbitmq:3.13.0-management
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: my-rabbit
    container_name: rabbitmq

  redis:
    image: redis/redis-stack:latest
    ports:
      - "8001:8001"
      - "6379:6379"
    container_name: redis