name: Tests and Linting

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  redis-container:
    runs-on: ubuntu-latest
    timeout-minutes: 20
  
    steps:
    - name: Start container
      run: |
        docker run -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:latest

  rabbitmq-container:
    runs-on: ubuntu-latest
    timeout-minutes: 20
  
    steps:
    - name: Start container
      run: |
        docker run -d --hostname my-rabbit --name rabbitmq -p 15672:15672 -p 5672:5672 rabbitmq:3.13.0-management 

  python:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        python: ["3.11"]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Setup Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
    
    - name: Install dependencies
      run: make install

    - name: Run linting check
      run: make check_lint

    - name: Run formatting check
      run: make check_format

    - name: Run types check
      run: make check_types

    - name: Run tests
      run: make test
